const DEFAULT_TOKEN_LENGTH = 7;
const DEFAULT_NUMBER_OF_TOKENS_TO_RETURN_TO_CLIENT = 10_000;
const TOKEN_DOES_NOT_EXIST = "Token Does Not Exist";

module.exports = {
  DEFAULT_TOKEN_LENGTH,
  DEFAULT_NUMBER_OF_TOKENS_TO_RETURN_TO_CLIENT,
  TOKEN_DOES_NOT_EXIST,
};
